### ISSUE TITLE
Bug in `explore_level`

### ISSUE THREAD

**Issue by Felixvillas** [CommanderCero/NetPlay#6]
Hi~

I found a bug (maybe not) in the `explore_level` skill, which, although it doesn't occur often, can cause the program to hang.

During the exploration process, there might be a situation like this: when executing one of the 8 movements (such as 'southwest'), if there happens to be a monster at the 'southwest' position, the environment might pop up a window and display a message like "Really attack the xxx?" (with 'xxx' being the monster, for example, 'goblin'). I'm not sure if a similar message would pop up if it's not a goblin but some other type of monster. Moreover, this pop-up does not trigger the termination of skills and the activation of LLMs, thereby causing the program to hang and be unable to continue running.

**Comment by Felixvillas** [comment]
Here is a screenshot of the game that triggered the bug.

![Uploading 1721133541223.jpg…]()

**Comment by Felixvillas** [comment]
Here is the screenshot of the bug.
 
![1721133541223](https://github.com/user-attachments/assets/e6779da5-5634-4eb4-a73d-b36aff7a3767)

**Comment by Felixvillas** [comment]
Sorry. 
For `explore_level`, I realized that I commented out `@fail_on_popup`, which caused the program to hang. And I commented out `@fail_on_popup` in order to `kick door` within `explore_level`.

**Comment by Felixvillas** [comment]
I set `avoid_monsters=True` in the `move_to` of `explore_level`.

I'll report under this issue whether this operation can avoid the popup during the skill `explore_level`.

**Comment by Felixvillas** [comment]
Bug using `avoid_monsters`: https://github.com/CommanderCero/NetPlay/blob/6487da46b357e17c1e1c96e67942363fff1393d6/netplay/core/agent_base.py#L230

It seems that the `avoid_monsters` parameter passed to the function is not effective. What is still being used is the `self.avoid_monsters` initialized by the class itself.

@CommanderCero

**Comment by CommanderCero** [comment]
Hey, sorry for the delayed response!

While there are cases in which I cannot detect popups (as nle just doesnt report them properly), attacking monsters are not the case. But you already figured out that you disabled fail_on_popup. However, I'm a bit confused why this dialogue showed up in the first place.

I would recommend to avoid the avoid_monsters flag (no pun intended).
I've added it in the hopes to give the LLM more control over when to engage in combat and when not (particularly as it often gets stuck behind shopkeepers, which always trigger the dialogue you mentioned).
However, not only does the LLM not use this feature properly it has a lot of issues. In particular it causes the agent to often get stuck in places. Its not well implemented so I should have removed it instead of keeping it.

**Comment by Felixvillas** [comment]
Thank you for the reply！no need to say sorry. I will modify the code according to my own thoughts, thank you！
